services:
  ice:
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
        tags:
          - registry-1.docker.io/oughtinc/ice:0.2.0
    image: ${COMPOSE_IMAGE:-ice}
