services:
  ice:
    build:
      context: .
      dockerfile: torch.Dockerfile
      x-bake:
        platforms:
          - linux/amd64
        tags:
          - docker.io/oughtinc/ice:0.2.0-torch
    image: ${COMPOSE_IMAGE:-ice-torch}
