services:
  ice:
    image: docker.io/oughtinc/ice:0.2.0-torch
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
