- name: Experiments end-to-end with Elicit-style QA for search
  results_json: "experiments/results/consort/experiments_search_elicit_prompt_multi_then_answer_then_enumerate.json"
  args:
    method: ice.recipes.consort_flow.baselines.elicit_baseline_prune_then_answer
    split: validation
    gold_standard_type: ice.recipes.experiments_and_arms.types.ExperimentsArms
    gold_standard_to_trials: ice.recipes.consort_flow.generate_questions.experiments_questions_and_answers_str
    answer_eval_method: ice.recipes.meta.eval_paper_qa.quick_question_driven_eval.quick_eval
    classification_eval_method: ice.recipes.meta.eval_paper_qa.common_eval_methods.eval_text_classification