- name: Qasper end-to-end with Elicit-style QA for search
  results_json: "experiments/results/consort/qasper_search_elicit_prompt_multi_then_answer_then_enumerate.json"
  args:
    method: ice.recipes.consort_flow.baselines.elicit_baseline_into_answer
    split: train # Anything other than "train" will use the val set
    answer_eval_method: ice.recipes.meta.eval_paper_qa.quick_question_driven_eval.quick_eval
    classification_eval_method: ice.recipes.meta.eval_paper_qa.common_eval_methods.eval_text_classification
    max_papers: 1