name: Deploy preview app
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  deploy-frontend-preview:
    name: Deploy frontend preview on Vercel
    runs-on: ubuntu-latest

    environment:
      name: ice-pr-${{ github.event.number }}-frontend
      url: ${{ steps.vercel-deploy.outputs.frontend_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: https://registry.npmjs.org/

      - name: Deploy on Vercel
        id: vercel-deploy
        run: |
          export FRONTEND_PREVIEW_URL=$(npx vercel --confirm --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_TEAM_ID }})
          echo "frontend_url=${FRONTEND_PREVIEW_URL}" >> $GITHUB_OUTPUT
