name: Tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - name: Build ICE
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: true
          cache-from: |
            type=gha, scope=dev
          cache-to: |
            type=gha, scope=dev
          tags: |
            ice:latest

      - name: Run all tests
        run: scripts/run-tests-action.sh
        env:
          COMPOSE_DOCKER_CLI_BUILD: "1"
          DOCKER_BUILDKIT: "1"
          COMPOSE_IMAGE: ice:latest
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
          OUGHT_INFERENCE_API_KEY: ${{ secrets.OUGHT_INFERENCE_API_KEY }}
